package view;

import javafx.scene.control.ScrollPane;
import javafx.scene.text.Text;

/**
 * The ScoreSubScene is a view for the ScoreCard Object. It shows past scores.
 */
public class ScoreSubScene extends SnapSubScene {
	private Text title;
	private Text text;
	private ScrollPane scorePane;
	private String scores;

	/**
	 * The ScoreCard view is instantiated with "no scores found",
	 * if it is not updated, that is what will be displayed.
	 */
	public ScoreSubScene() {
		initialiseScorePane();
		setTitle();
		initialiseScoreCard();
		scores = new String("No scores found!");
		setText();
	}


	private void initialiseScoreCard() {
		this.getPane().getChildren().add(title);
		this.getPane().getChildren().add(scorePane);
		positionNode(title, 100, 80);
		positionNode(scorePane, 65, 100);
	}

	
	private void initialiseScorePane() {
		scorePane = new ScrollPane();
		scorePane.setPrefSize(300, 300);
		scorePane.setContent(text);	
	}
	
	private void setTitle() {
		title = makeText("PREVIOUS GAMES\n*******************", 22);
	}
	
	private void setText() {
		text = makeText(scores, 10);
	}

	/**
	 * Takes a string generated by the ScoreCard object, and updates the view with the
	 * latest game results.
	 * @param scores
	 * - game results generated by ScoreCard object
	 */
	public void updateScores(String scores) {
		if (scores != null && scores.trim().length() > 0)
			this.scores = scores;
		this.getPane().getChildren().remove(text);
		setText();
		scorePane.setContent(text);	
	}

}